cc_library(
    name = "ENCasualTimeParser",
    hdrs = [
        "ENCasualTimeParser.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//src/parsers",
    ],
)

cc_library(
    name = "ENCasualDateParser",
    hdrs = [
        "ENCasualDateParser.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//src/parsers",
    ],
)

cc_library(
    name = "ENDeadlineFormatParser",
    hdrs = [
        "ENDeadlineFormatParser.hpp",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//src/parsers",
    ],
)
