cc_library(
    name = "ENCasualTimeParser",
    hdrs = [
        "ENCasualTimeParser.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//src/parsers",
    ],
)
