cc_library(
    name = "parsers",
    srcs = [
        "parsers.cc",
    ],
    hdrs = [
        "parsers.hpp",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//src:result",
    ],
)
