cc_library(
    name = "utilities",
    hdrs = [
        "utils.hpp",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
#	"@boost//:date_time",
    ],
    visibility = ["//visibility:public"],
)
