
cc_library (
    name = "result",
    srcs = [
        "result.cc",
    ],
    hdrs = [
        "result.h",
    ],
    deps = [
        "//src/utils:utilities",
	#"@boost//:date_time",
    ],
    visibility = ["//visibility:public"],
)

