cc_library(
    name = "result",
    srcs = [
        "result.cc",
    ],
    hdrs = [
        "result.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/utils:utilities",
        #"@boost//:date_time",
    ],
)
